packageName: kabanero-operator
channels:
- name: alpha
  currentCSV: kabanero-operator.v0.4.0
- name: release-0.3
  currentCSV: kabanero-operator.v0.3.0
- name: release-0.4
  currentCSV: kabanero-operator.v0.4.0
defaultChannel: alpha

