kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: codewind-rolebinding
subjects:
- kind: ServiceAccount
  name: che-workspace
roleRef:
  kind: ClusterRole
  name: eclipse-codewind
  apiGroup: rbac.authorization.k8s.io
