apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: kabanero-catalog
  namespace: openshift-marketplace
  labels:
    kabanero.io/install: 00-catalogsource
spec:
  sourceType: grpc
  image: kabanero/kabanero-operator-registry:latest
  publisher: kabanero.io
  displayName: Kabanero Operators
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elasticsearch-operator
  namespace: openshift-operators
  labels:
    kabanero.io/install: 10-subscription
spec:
  channel: "4.2"
  installPlanApproval: Automatic
  name: elasticsearch-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jaeger-product
  namespace: openshift-operators
  labels:
    kabanero.io/install: 10-subscription
spec:
  channel: stable
  installPlanApproval: Automatic
  name: jaeger-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kiali-ossm
  namespace: openshift-operators
  labels:
    kabanero.io/install: 10-subscription
spec:
  channel: stable
  installPlanApproval: Automatic
  name: kiali-ossm
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator
  namespace: openshift-operators
  labels:
    kabanero.io/install: 11-subscription
spec:
  channel: "1.0"
  installPlanApproval: Automatic
  name: servicemeshoperator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: knative-eventing-operator-alpha-community-operators-openshift-marketplace
  namespace: openshift-operators
  labels:
    kabanero.io/install: 12-subscription
spec:
  channel: alpha
  config:
    resources: {}
  installPlanApproval: Automatic
  name: knative-eventing-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: knative-eventing-operator.v0.8.0
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: serverless-operator
  namespace: openshift-operators
  labels:
    kabanero.io/install: 12-subscription
spec:
  channel: kabanero-release-0.3.0
  installPlanApproval: Automatic
  name: serverless-operator
  source: kabanero-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: serverless-operator.v1.1.0
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator-dev-preview-community-operators-openshift-marketplace
  namespace: openshift-operators
  labels:
    kabanero.io/install: 13-subscription
spec:
  channel: dev-preview
  config:
    resources: {}
  installPlanApproval: Automatic
  name: openshift-pipelines-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: openshift-pipelines-operator.v0.7.0
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: appsody-operator-certified-beta-certified-operators-openshift-marketplace
  namespace: openshift-operators
  labels:
    kabanero.io/install: 13-subscription
spec:
  channel: beta
  config:
    resources: {}
  installPlanApproval: Automatic
  name: appsody-operator-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: v1
kind: Namespace
metadata:
  name: kabanero
  labels:
    kabanero.io/install: 14-subscription
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: kabanero
  namespace: kabanero
  labels:
    kabanero.io/install: 14-subscription
spec:
  targetNamespaces:
  - kabanero
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: eclipse-che
  namespace: kabanero
  labels:
    kabanero.io/install: 14-subscription
spec:
  channel: stable
  installPlanApproval: Automatic
  name: eclipse-che
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: eclipse-che.v7.3.0
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kabanero-operator
  namespace: kabanero
  labels:
    kabanero.io/install: 14-subscription
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: kabanero-operator
  source: kabanero-catalog
  sourceNamespace: openshift-marketplace
---
