apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    kabanero.io/install: 20-cr-servicemeshcontrolplane
    kabanero.io/namespace: 'true'
---
apiVersion: maistra.io/v1
kind: ServiceMeshControlPlane
metadata:
  name: basic-install
  namespace: istio-system
  labels:
    kabanero.io/install: 20-cr-servicemeshcontrolplane
spec:
  istio:
    global:
      multitenant: true
      proxy:
        autoInject: disabled
      omitSidecarInjectorConfigMap: true
      disablePolicyChecks: false
      defaultPodDisruptionBudget:
        enabled: false
    istio_cni:
      enabled: true
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: false
        type: LoadBalancer
      istio-egressgateway:
        enabled: false
      cluster-local-gateway:
        autoscaleEnabled: false
        enabled: true
        labels:
          app: cluster-local-gateway
          istio: cluster-local-gateway
        ports:
          - name: status-port
            port: 15020
          - name: http2
            port: 80
            targetPort: 8080
          - name: https
            port: 443
    mixer:
      enabled: false
      policy:
        enabled: false
      telemetry:
        enabled: false
    pilot:
      autoscaleEnabled: false
      sidecar: false
    kiali:
      enabled: false
    tracing:
      enabled: false
    prometheus:
      enabled: false
    grafana:
      enabled: false
    sidecarInjectorWebhook:
      enabled: false
---
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: istio-system
  labels:
    kabanero.io/install: 21-cr-servicemeshmemberrole
spec:
  members:
  - knative-serving
  - tekton-pipelines
  - kabanero
---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
  labels:
    kabanero.io/install: 22-cr-knative-serving
    kabanero.io/namespace: 'true'
---
apiVersion: serving.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
  labels:
    kabanero.io/install: 22-cr-knative-serving
---
apiVersion: kabanero.io/v1alpha1
kind: Kabanero
metadata:
  name: kabanero
  namespace: kabanero
  labels:
    kabanero.io/install: 23-cr-kabanero
spec:
  version: "0.2.0"
  collections: 
    repositories: 
    - name: central
      url: https://github.com/kabanero-io/collections/releases/download/0.2.0/kabanero-index.yaml
      activateDefaultCollections: true
---
