kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kabanero-operator
subjects:
- kind: ServiceAccount
  name: kabanero-operator
  namespace: kabanero
roleRef:
  kind: ClusterRole
  name: kabanero-operator
  apiGroup: rbac.authorization.k8s.io
